### PR TITLE
suggestion to fix color issues

### PR DESCRIPTION
**Pull request by offer-shmuely**

### CODE REVIEW

**Comment by MRC3742** [comment]
I've tested this PR on a T16 running OTX with the Darkblue theme and it is partially working.
The OTX Darkblue theme is a good test bed as it normally uses White text on a Dark background.
There are many items that still show the White text and I went ahead fixed a few but then realized that any line with CUSTOM_COLOR added creates a "Syntax error" when trying to load the script on any B&W screen TX.
This approach would only be able to be used on the color LCD models and breaks the script for use on all other TX's.

I think the answer is use the original script but figure a way to restore the original theme colors before exit.
The EVT_EXIT_BREAK does accomplish this but does not work if a long press exit is used to terminate the script. 
Could a popup box be added to ask if we really want to exit the script and then use this command to accomplish this?

We could also have the script default as "local color = 0" keeping the default theme colors.

Rich

**Comment by offer-shmuely** [comment]
it is almost impossible to make sure you run code on exit.
it will just make the times that the tx "corrupt it's color" less frequent
I do not this is a good way to go

**Comment by offer-shmuely** [comment]
I suggest to keep the color only on splash screen, and later on the title.
and use the user defaults (he did choose a theme after all) for all the rest

try the new update...

**Comment by MRC3742** [comment]
the updated script will still not run on the B&W radios.
CUSTOM_COLOR will cause an error on first read on any B&W radio.

line 259 is  "lcd.drawText(midpx-wfpx*5.8, hfpx,"RX Statistics", bigSiz + CUSTOM_COLOR)"

screenshot_x9d+_23-04-01_23-38-40

Rich

**Comment by MikeBland** [comment]
I've just experimented using:
local function drawText( x, y, text, attr )
  if LCD_W == 480 and color ~= 0 then
    lcd.setColor(CUSTOM_COLOR, RED)
    attr = attr + CUSTOM_COLOR
  end
  lcd.drawText( x, y, text, attr )
end
and changing all lcd.drawText calls to drawText.

This works (on erskyTx) on both a TX16S (colour) and a X9LiteS (B&W). On the colour display the text is in RED, and the B&W display just works.

The condition "if LCD_W == 480 and color ~= 0" could be combined into a single variable to make the test execute quicker.
The required colour could be passed in as an extra parameter, or could be placed in a global variable if most text needs to be the same colour.

**Comment by MRC3742** [comment]
@MikeBland 
I just tried your code out on the Activation script using black text and it works!
It now loads and displays correctly on B&W versions and on LCD versions leaves theme colors unchanged on exit.

There is still one issue with LCD versions.
The "SelectedItem" text is also Black but needs to be White or can't be seen ?
Any suggestions for this problem?

screenshot_t16_23-04-02_23-33-51

Rich

**Comment by MikeBland** [comment]
Interesting as the text IS white on erskyTx for the selected item. It seems openTx is using the specified colour unconditionally, while erskyTx also takes action of the INVERS flag and complements the specified colour.

**Pull request closed without merging**
