### PR TITLE
update file names & display text

### PR DESCRIPTION
**Pull request by offer-shmuely**

### CODE REVIEW

**Comment by offer-shmuely** [comment]
@MRC3742 please take a look

**Comment by MRC3742** [comment]
The problem is we are using the same script on many different radios and operating platforms.
The tool name is not currently available on erskyTX and only the lua file name is shown.
With the changes to the tool name B&W screens only allow 16 characters or revert back to the filename.
"TNS|UNI Statistics v6|TNE" is 17 characters and displays OK in the 480 size tools page but not on the B&W screen where now the filename is shown. (with the hyphen and no version number)

screenshot_x7_23-04-01_22-44-47

Every change that is made effects different screen sizes differently and needs to be checked on all sizes for fit.
I start with the 128 x 64 screen size and then will check on the larger screens for fit.
The addition of "UNI" to the title line of the splash screen.
screenshot_x7_23-04-01_22-07-57

"RESET" just fits on the 128 screen and "RESET NOW" does not.
Auto Tuning crowds the number and hides the "-" but "Auto Tune" would fit and make more sense than "Tuning"
The other option would be to move the tune number to the right to add some space.
The point is whatever changes are made it needs to work across all screen sizes and  operating systems.
screenshot_x7_23-04-01_22-20-57

Rich

**Comment by offer-shmuely** [comment]
So we can go with:
"TNS|UNI Stat v6|TNE"

I will change the reset-now back to "reset" 
Although i think it is not clear,
It should be something like: "restore to default" - "restore now"


It better to keep the auto-tuning, and adjust the value

I will see what can done about the splash screen

Regarding to ersky, it is not related, it run the basic files, not the lua

**Comment by MRC3742** [comment]
Yes, erskyTx currently does currently support lua and that also brings another screen size into the mix.

erskyTx on the X9D models uses 11 pixel wide screen columns on both sides for button navigation limiting the screen width available for lua to 190 x 64.
Most posts back at the Aloft UNI-RX Setup script thread, starting on page 2, were about allowing lua to run on erskyTx with MikeB making firmware changes to also run a compiled .luac to save memory and various sizing and alignment issues. The latest problem he was having was text background on color screens. (I think he has fixed that firmware issue by moving the text down a layer)

Many changes you have suggested are working and bring better clarity to the script.
I was just pointing out the problems of changing items that will still allow operation on all platforms used.
After all we want a uni-script to work with UNI-RX firmware!  :-)

Rich

**Comment by offer-shmuely** [comment]
Ok, so what of the changes to revert?
By the way, why do we use font that are larger from the regular system fonts? 
Maybe if we use smaller fonts (at the size of the regular model settings) the life will be easier?

**Comment by MRC3742** [comment]
(1) I think that the statistics script name would be better descriptive with "TNS|UNI Stats v6|TNE" ?
(2) The splash screens already lists "for UNI-RX firmware" on the third line, I don't see the need to also list it on the first ?
(3) Unless we can come up with a better and shorter description, then "RESET" will have to stay as is ?
(4) "AUTO TUNING" can stay but move the value right with line 327 to "lcd.drawNumber(midpx+wfpx*3.2, ty, tvalue, txtSiz_R)" ?
(5) The rest of the changes all work fine and are improvement to the scripts.

The size font on all B&W screens used is the standard size font but we are limited to screen width as explained above.
Using the same script as the B&W screens, the LCD screens screens larger font is used for better readability.
Using standard text on LCD screens would just make everything smaller but still be restricted by the 128 screen displays.
It's all a compromise for use across the different screen widths.

Rich

**Comment by offer-shmuely** [comment]
Yes (ok) to 1,2,3,4 

Font size: there is no need to better readability, when all the other setting font are on other size, it make the look & feel strange and less "professional look"

**Comment by offer-shmuely** [comment]
updated the pr with the fixes specified above

**Comment by MRC3742** [comment]
Not sure how larger text is a less "professional look" but everyone has their own opinion?
We have a larger screen constrained by limited length text from smaller screens. Why not use it?
I certainly prefer being able to see the screen without squinting.

I would still like to keep the larger text and custom colors as an option with the defaults set to small text and user theme colors.
PR #6  

Rich

**Pull request merged**
